### ISSUE TITLE
Add K8s examples

### ISSUE THREAD

**Issue by jkone27** [UnoSD/Pulumi.FSharp.Extensions.Examples#1]
k8s has many different implementations / namespaces,  is not super clear how to use it

from docs is clear but when referencing the lib not as much..

**Comment by UnoSD** [comment]
I don't have an active cluster that I use, but there is an example in the Test project here: https://github.com/UnoSD/Pulumi.FSharp.Extensions/blob/master/Pulumi.FSharp.NuGet.Test/Program.fs

not sure if that works, but I built a real cluster, if I find the code, I'll put it up in the library

**Comment by UnoSD** [comment]
here you go: https://github.com/UnoSD/Pulumi.FSharp.Extensions.Examples/tree/main/Kubernetes/AKSCluster

it's quite an old template, so it needs testing and polishing
